//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamEZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int InfoID { get; set; }
        public string About { get; set; }
        public string WhatWeDo { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string FaceBook { get; set; }
        public string Twitter { get; set; }
        public string Gmail { get; set; }
    }
}
